### ISSUE TITLE
missing errormessage if directory does not exist

### ISSUE THREAD

**Issue by rubo77** [ffnord/mesh-announce#34]
If you specify a directory with `-d` that does not exist, the service runs luckily anyway, although it doesn't find any provider!

**Comment by TobleMiner** [comment]
Can't reproduce

```
sudo /opt/mesh-announce/respondd.py -d /non-existent-directory -i br-ffki -i ffki-mvpn -b bat-ffki -m 10.116.160.1
Traceback (most recent call last):
  File "/opt/mesh-announce/respondd.py", line 70, in <module>
    get_handler(get_providers(args.directory), {'batadv_dev': args.batadv_iface, 'mesh_ipv4': args.mesh_ipv4})
  File "/opt/mesh-announce/providers/__init__.py", line 150, in get_providers
    raise FileNotFoundError("The path '{}' is not a valid directory".format(directory))
FileNotFoundError: The path '/non-existent-directory' is not a valid directory
```

**Comment by rubo77** [comment]
I used

    /opt/mesh-announce/provider

Without s

**Comment by rubo77** [comment]
strange, I think it was running before with thy typo in the path, but I cannot reproduce it now either
